services:
  rabbitmq:
      image: rabbitmq:management
      environment:
        RABBITMQ_LOGS: "-w"
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - todo-network
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq

  auth_micro:
    build:
      context: ./auth_micro
    ports:
      - "8000:8000"
    networks:
      - todo-network
    env_file:
      - .development.env
    depends_on:
      - auth-db
      - rabbitmq
    restart: always  

  todo_micro:
    build:
      context: ./todo_micro
    ports:
      - "8003:8000"
    networks:
      - todo-network
    env_file:
      - .development.env
    depends_on:
      - todo-db
      - rabbitmq
    restart: always  
  

  auth-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_micro
    ports:
      - "5433:5432" 
    networks:
      - todo-network
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  todo-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_micro
    ports:
      - "5434:5432" 
    networks:
      - todo-network
    volumes:
      - todo-db-data:/var/lib/postgresql/data

networks:
  todo-network:
    driver: bridge

volumes:
  auth-db-data:
  todo-db-data:
  rabbitmq-data:
